services:
 app:
  ports:
   - "${APP_PORT:-8000}:8000"
  volumes:
    - type: bind
      source: ./src
      target: /var/www/html
    - type: bind
      source: ./docker/app/default.conf
      target: /etc/nginx/conf.d/default.conf
  build: ./docker/app
 
 db:
  environment:  
   -  "MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:?envが設定されていません}"
   - "MYSQL_USER=${DB_USERNAME:?envが設定されていません}"
   - "MYSQL_PASSWORD=${DB_PASSWORD:?envが設定されていません}"
   - "MYSQL_DATABASE=${DB_DATABASE:?envが設定されていません}"
   - TZ=Asia/Tokyo
  ports:
   - "${DB_PORT:?envが設定されていません}:3306"
  volumes:
   - type: volume
     source: db-compose-volume
     target: /var/lib/mysql
   - type: bind
     source: ./docker/db/init
     target: /docker-entrypoint-initdb.d
  image: mysql:8.3.0

 mail:
  environment:
   - TZ=Asia/Tokyo
   - MP_DATA_FILE=/data/mailpit.db
  ports:
   - "${MAIL_PORT:-8025}:8025"
  volumes:
   - type: volume
     source: mail-compose-volume
     target: /data
  image: axllent/mailpit:v1.10.1

volumes:
 db-compose-volume:
 mail-compose-volume:

